---
version: '3.4'
x-extra_hosts: &extra_hosts
  pult: 192.168.1.22
  uov: 192.168.1.23
  servertop: 192.168.1.24
  armn: 192.168.1.25
  devs: 192.168.1.26

x-command: &command bash -c "mkdir -p /home/kar-pa/src/tops-kar-pa ; mount \"${WORKSPACE}\" /home/kar-pa/src/tops-kar-pa --bind ; /etc/init.d/ssh start &&  sleep infinity"

x-volumes: &volumes
      - .:$WORKSPACE
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.XIM-unix:/tmp/.XIM-unix

x-environment: &environment
      - DISPLAY=unix$DISPLAY
      - USER=kar-pa

services:

  pult:
    image: kar
    build: .
    hostname: pult
    networks:
      kar:
        ipv4_address: 192.168.1.22
    extra_hosts: *extra_hosts
    volumes: *volumes
    command: *command
    privileged: true
    environment: *environment

  servertop:
    image: kar
    hostname: servertop
    networks:
      kar:
        ipv4_address: 192.168.1.24
    depends_on:
      - "pult"
    privileged: true
    volumes: *volumes
    command: *command
    environment: *environment

  devs:
    image: kar
    hostname: devs
    networks:
      kar:
        ipv4_address: 192.168.1.26
    depends_on:
      - "pult"
    privileged: true
    volumes: *volumes
    command: *command
    environment: *environment

networks:
  kar:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
