@Library('mattermostNotify') _

pipeline {
//    agent { dockerfile true }
	agent any
    stages {
        stage('Init') {
            steps {
        			sh 'docker-compose build'        			
        			sh 'docker-compose up -d'
        			sh 'docker-compose exec -T pult bash -c \"chown -R kar-pa.kar-pa $(dirname $WORKSPACE)\" '
        			sh 'docker-compose exec -T pult bash -c \"mkdir /home/kar-pa/src/tops-kar-pa ;mount $WORKSPACE /home/kar-pa/src/tops-kar-pa --bind\" '
        			sh 'docker-compose exec -T servertop bash -c \"mkdir /home/kar-pa/src/tops-kar-pa ;mount $WORKSPACE /home/kar-pa/src/tops-kar-pa --bind\" '
        			sh 'docker-compose exec -T devs bash -c \"mkdir /home/kar-pa/src/tops-kar-pa ;		mount $WORKSPACE /home/kar-pa/src/tops-kar-pa --bind\" '
        			sh 'docker-compose up -d'
 	           }
        }

        stage('Build') {
            steps {
        			sh 'docker-compose exec -u kar-pa -T pult bash -c \"/home/kar-pa/src/tops-kar-pa/scripts/build_and_upload.sh -debug\"'
        			sh 'docker-compose exec -u kar-pa -T pult bash -c \"/home/kar-pa/src/tops-kar-pa/scripts/build_pult.sh -debug\"'
 	           }
        }

    }
    post {
        always { 
         sh 'docker-compose exec -T pult bash -c \"chown -R $UID $WORKSPACE/\" '
         sh 'docker-compose down'
        }
        failure {
                script {
		    mattermostNotify.send("Build",
		    					 "https://redmine.rtc.ru:8181/scm/hg/tops-kar-pa/rev",
		    					 "http://redmine.rtc.ru:8065/hooks/9towish683fydg8n3g8m3zb5ph")
		    }
        }
    }
}
